// Demo data for local preview (no Firebase)
export const gifts = [
  {
    id: 'honeymoon-1',
    title: 'Honeymoon Flights to Maui',
    description: 'Help us get to paradise. Any contribution moves the plane ✈️',
    category: 'honeymoon',
    categoryLabel: 'Honeymoon',
    imageUrl: '',
    allowPartial: true,
    goalAmount: 2000,
    amountFunded: 760,
    rank: 10,
  },
  {
    id: 'kitchen-1',
    title: 'Stand Mixer',
    description: 'For endless cookies and weekend pasta.',
    category: 'kitchen',
    imageUrl: '',
    allowPartial: false,
    price: 349,
    amountFunded: 0,
    rank: 8,
  },
  {
    id: 'home-1',
    title: 'Cozy Throw Blanket',
    description: 'Movie nights just got better.',
    category: 'home',
    imageUrl: '',
    allowPartial: false,
    price: 59,
    amountFunded: 0,
    rank: 5,
  },
  {
    id: 'experience-1',
    title: 'Date Night: Tasting Menu',
    description: 'A celebratory dinner for two.',
    category: 'experience',
    imageUrl: '',
    allowPartial: true,
    goalAmount: 250,
    amountFunded: 100,
    rank: 7,
  },
];
